# Generated by Django 4.2.5 on 2023-09-16 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0002_remove_countrydata_access_remove_countrydata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
