# Generated by Django 4.2.5 on 2023-09-17 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0003_country_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cambodia_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambodia', to='country.countrydata'),
        ),
        migrations.AlterField(
            model_name='country',
            name='laopdr_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laopdr', to='country.countrydata'),
        ),
        migrations.AlterField(
            model_name='country',
            name='thailand_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thailand', to='country.countrydata'),
        ),
        migrations.AlterField(
            model_name='country',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='vietnam_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vietnam', to='country.countrydata'),
        ),
    ]
